[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "fastapi-k8s-demo"
version = "0.1.0"
dependencies = [
    "fastapi>=0.110",
    "uvicorn[standard]>=0.27"
]
